#! /bin/bash

CONF_FILE="compiletime-settings"

if [ "$1" != "" ]; then
  if [ "${1#--}" = "$1" ]; then
    CONF_FILE=$1
    if [ "$CONF_FILE" = "-d" ]; then
      CONF_FILE=compiletime-settings.devel
    fi
    shift
  fi
fi

if [ ! -f $CONF_FILE ]; then
  echo "$CONF_FILE cannot be opened"
  exit 1
fi

SUFFIX=""
while [ "$1" != "" ]; do
  SUFFIX="$SUFFIX $1"
  shift
done

CONF=`cat $CONF_FILE`
CONF=`echo -n "$CONF"|tr '\n' ' '|cut '-d{' -f2|cut '-d}' -f1`

set $CONF

#echo "$*"

STRING=""
PLUGIN=""

while [ "$1" != "" ]; do
#  echo "$1 $2"

  case "$1" in
    experimental)
      if [ "$2" = "on" ]; then STRING="$STRING --enable-experimental"; fi
      ;;
    dodebug)
      if [ "$2" = "on" ]; then STRING="$STRING --enable-dodebug"; fi
      ;;
    net)
      if [ "$2" = "off" ]; then STRING="$STRING --enable-nonet"; fi
      ;;
    x)
      if [ "$2" = "off" ]; then STRING="$STRING --without-x"; fi
      ;;
    mitshm)
      if [ "$2" = "off" ]; then STRING="$STRING --enable-nomitshm"; fi
      ;;
    sbemu)
      if [ "$2" = "off" ]; then STRING="$STRING --enable-nosbemu"; fi
      ;;
    slangforce)
      if [ "$2" = "on" ]; then STRING="$STRING --enable-force-slang"; fi
      ;;
    runasroot)
      if [ "$2" = "on" ]; then STRING="$STRING --enable-runasroot"; fi
      ;;
    linkstatic)
      if [ "$2" = "on" ]; then STRING="$STRING --enable-linkstatic"; fi
      ;;
    cpuemu)
      if [ "$2" = "on" ]; then STRING="$STRING --enable-cpuemu"; fi
      ;;
    newint)
      if [ "$2" = "on" ]; then STRING="$STRING --enable-new-intcode"; fi
      ;;
    aspi)
      if [ "$2" = "on" ]; then STRING="$STRING --enable-aspi"; fi
      ;;
    svgalib)
      if [ "$2" = "on" ]; then STRING="$STRING --enable-use-svgalib"; fi
      ;;
    pthreads)
      if [ "$2" = "on" ]; then STRING="$STRING --enable-use-pthreads"; fi
      ;;
    plugin_*)
      plugin=`expr substr $1 8 100`
      if [ "$2" = "on" ]; then PLUGIN="$PLUGIN $plugin yes"; fi
      if [ "$2" = "off" ]; then PLUGIN="$PLUGIN $plugin no"; fi
      ;;
    *)
      ;;
  esac

  shift; shift;
done

echo "mkpluginhooks enable $PLUGIN"
./mkpluginhooks enable $PLUGIN

echo ". ./base-configure $STRING $SUFFIX"
. ./base-configure $STRING $SUFFIX
