#! /bin/bash

CONF_FILE="compiletime-settings"

if [ "$1" != "" ]; then
  if [ "${1#--}" = "$1" ]; then
    CONF_FILE=$1
    shift
  fi
fi

if [ ! -f $CONF_FILE ]; then
  echo "$CONF_FILE cannot be opened"
  exit 1
fi

SUFFIX=""
while [ "$1" != "" ]; do
  SUFFIX="$SUFFIX $1"
  shift
done

set `cut '-d{' -f2 $CONF_FILE |cut '-d}' -f1`

#echo "$*"

STRING=""

while [ "$1" != "" ]; do
#  echo "$1 $2"

  case "$1" in
    novm86plus)
      if [ "$2" = "on" ]; then STRING="$STRING --enable-novm86plus"; fi
      ;;
    dodebug)
      if [ "$2" = "on" ]; then STRING="$STRING --enable-dodebug"; fi
      ;;
    newkbd)
      if [ "$2" = "on" ]; then STRING="$STRING --enable-new-kbd"; fi
      ;;
    x)
      if [ "$2" = "off" ]; then STRING="$STRING --without-x"; fi
      ;;
    mitshm)
      if [ "$2" = "off" ]; then STRING="$STRING --enable-nomitshm"; fi
      ;;
    sbemu)
      if [ "$2" = "off" ]; then STRING="$STRING --enable-nosbemu"; fi
      ;;
    slangforce)
      if [ "$2" = "on" ]; then STRING="$STRING --enable-force-slang"; fi
      ;;
    tmonoton)
      if [ "$2" = "on" ]; then STRING="$STRING --enable-monoton-timing"; fi
      ;;
    runasroot)
      if [ "$2" = "on" ]; then STRING="$STRING --enable-runasroot"; fi
      ;;
    linkstatic)
      if [ "$2" = "on" ]; then STRING="$STRING --enable-linkstatic"; fi
      ;;
    newx)
      if [ "$2" = "on" ]; then STRING="$STRING --enable-new-X"; fi
      ;;
    newport)
      if [ "$2" = "on" ]; then STRING="$STRING --enable-new-port"; fi
      ;;
    *)
      ;;
  esac

  shift; shift;
done

echo "./configure $STRING $SUFFIX"
./configure $STRING $SUFFIX
