#!/bin/sh
if test "$1" = "-d"; then
  if test -d .git; then
    # need -n 1 for merge commits
    git log HEAD^..HEAD -n 1 --format=%cd --date=short
  else
    date -r VERSION +%F
  fi
else
  if test -d .git; then
    s=`git describe --tags --match "dosemu2-[0-9]*" HEAD 2>/dev/null | sed -e 's/^dosemu2-//' -e 's/-.\+-/-/'`
    if [ -z "$s" ]; then
      s=`cat VERSION`
    fi
  else
    s=`./git-describe-remote.awk https://github.com/stsp/dosemu2.git | sed -e 's/^dosemu2-//'`
    if [ -z "$s" ]; then
      s=`cat VERSION`
    fi
  fi
  echo $s
fi
