#!/bin/sh
SRC=$1
DEST=$2
shift 2
FILES=$*
if [ -z "$TMP" ]
then
  TMP=/tmp
fi
TMPFILE=$TMP/mkbkup.$$

for x in $FILES
do
	if [ -r "$SRC/$x" ]
	then
 	  if [ "$SRC/$x" -nt "$DEST/$x" -o ! -r "$DEST/$x" ]
	  then
		echo "Backing up $x"
		diff -u $DEST/$x $SRC/$x > $TMPFILE
		cp -b --version-control numbered $TMPFILE $DEST/${x}.diff
		cp -b --version-control numbered $SRC/$x $DEST/$x
	 	rm $TMPFILE
  	  fi
	fi
done

