#! /bin/bash
#
# NOTE: Don _not_ use this, its only a tool for developers
#
# Build the 'base-configure' script, which should not called directly
# by users. Users should always call 'default-configure' or just
# simply 'make'
#

autorebuild()
{
  dir=$1
  (
    cd $dir
    if [ -f configure.in ]; then
      echo $dir
      autoconf
    fi
    if [ -f acconfig.h ]; then
      autoheader
    fi
  )
}
ln -sf base-configure.in configure.in
autorebuild .
rm -f base-configure
sed -e 's|#! /bin/sh|# DO NOT EXECUTE THIS exept via default-configure|' configure >base-configure
chmod 644 base-configure
rm -f configure configure.in

PLUG=plugin
DIR=src/$PLUG
if [ ! -d $DIR ]; then
  exit 1
fi
PDIRS=`cd $DIR; find ./ -maxdepth 1 -type d -printf ' %f'`
for dir in $PDIRS ; do 
  autorebuild $DIR/$dir
done
