#! /bin/sh
#
# execute this script, when you patched your dosemu distribution
# and want all scrpts to have the exec-bit set.

chmod 755 set-permissions # myself ;-)
chmod 755 ViewDocs
chmod 755 config.guess config.sub default-configure mkconfscript mkkeytables
chmod 755 mknewyear mkpluginhooks
chmod 644 base-configure
chmod 755 setup-dosemu submit-bug-report gnats/send-pr gnats/send-pr.sh
chmod 755 gnats/get-email.sh
chmod 755 setup/compiletime_setup.sh setup/runtime_setup.sh
chmod 755 setup/runtime_setup.tk setup/compiletime_setup.tk
chmod 755 install-sh rebuild
chmod 755 first-test
chmod 755 src/arch/linux/kversion.sh
chmod 755 src/tools/periph/getrom
chmod 755 src/doc/DANG/DANG_c.pl src/doc/DANG/make_DANG
chmod 755 dexe/do_mtools dexe/mkdexe dexe/extract-dos
chmod 755 dexe/myxcopy setup-hdimage dexe/check-mtools
chmod 755 setup-bootdir
chmod 755 src/tools/mkbindist
