#! /bin/sh
#
# execute this script, when you patched your dosemu distribution
# and want all scripts to have the exec-bit set.

chmod 755 set-permissions # myself ;-)
chmod 755 ViewDocs
chmod 755 config.guess config.sub default-configure mkkeytables
chmod 755 mknewyear mkpluginhooks
chmod 755 bisonpp.pl
chmod 755 configure
chmod 755 setup-dosemu
chmod 755 setup/compiletime_setup.sh setup/runtime_setup.sh
chmod 755 setup/runtime_setup.tk setup/compiletime_setup.tk
chmod 755 install-sh rebuild
chmod 755 src/arch/linux/kversion.sh
chmod 755 src/tools/periph/getrom
chmod 755 src/doc/DANG/DANG_c.pl src/doc/DANG/make_DANG
chmod 755 src/doc/tools/fixupSGML.pl
chmod 755 src/doc/tools/doSgmlTools.pl
chmod 755 dist/dosemu dist/mkbindist install_systemwide
