#!/bin/bash
#
# Front end to the runtime & compile time scripts.
#

if false; then #hash wish >/dev/null 2>&1; then
  if [ "$DISPLAY" != "" ]; then
    echo "
*** NOTE: setup-dosemu currently is only able to handle setup
***       via TclTk. Fortunately you have that installed ;-)
"
    mkdir -p ~/.dosemu/tmp
    cd setup
    exec ./setup.tk
  fi
fi

echo "
*** NOTE: setup-dosemu isn't correctly updated to the recent changes
***       in the configuration. 
***       Hence, don't use setup-dosemu at the moment !!
***       We will fix this later though.
***
***       In the meantime just do 'make' to compile DOSEMU and edit
***       the dosemu.conf, ~/.dosemurc and compiletime-settings files
***       manually.
***              --Bart, 20021214 
"
exit 1


TOPDIR=`pwd -P`
export TOPDIR
mkdir -p ~/.dosemu/tmp
TEMP=~/.dosemu/tmp/$0.$$

AWK=gawk
export AWK

. setup/select-dialog

FINISHED=0
if [ "@$DIALOG_SUPPORTS_CURRENT" = "@true" ];
then
  CURRENT=1
fi

while [ $FINISHED -ne 1 ]
do
  $DIALOG --backtitle "DOSEmu Configuration" \
    --title "Select Configuration to perform" \
    --menu "Choose the Configuration to perform:" 10 60 3 $CURRENT \
      1 "Compile time (runs ./configure)" \
      2 "Runtime (both System Wide, and personal)" \
      3 "Exit" 2> $TEMP
  
  RETVAL=$?
  if [ $RETVAL -eq 0 ]
  then
    RESULT=`cat $TEMP`

    if [ "@$DIALOG_SUPPORTS_CURRENT" = "@true" ];
    then
      CURRENT=$RESULT
    fi
    
    case $RESULT in 
      1)
        (cd setup; ./compiletime_setup.sh)
	;;
      2)
# we changed /etc/dosemu.conf
# as long as those changes aren't reflected, we disable it
# -- Hans 970115
echo "Sorry, this one is currently not working"
FINISHED=1
rm $TEMP
exit 1
        (cd setup; ./runtime_setup.sh)
        ;;
      3)
        FINISHED=1
        ;;
    esac
  elif [ $RETVAL -eq 2 ]
  then
    $DIALOG --backtitle 'DOSEmu configuration' --title 'Help' --msgbox 'Select "Compile time" to configure the DOSEmu compilation process and select which optional features are included. Select "Runtime" to configure the variables DOSEmu uses when it runs, such as the amount and type of memory to provide to applications.' 10 65
  else
    FINISHED=1
  fi
done

rm $TEMP    
