#! /bin/bash

echo "
The files ./doc/*.txt are BOLDFACE formatted. Apparently this confuses some of
our users, so we just supply this script to help them ;-)

What info do you want to be displayed ? (enter a number)
"
LIST="README.txt README-tech.txt configuration.txt bugreports.txt dosemu-HOWTO.txt "
CONF="dosemu.conf chapter"

select file in "$CONF"  $LIST; do
  if [ "$file" = "$CONF" ]; then
    line=`col -b <doc/README.txt| grep -n 'Runtime Configuration Options'|tail -n1|cut -d: -f1`
    less +$line ./doc/README.txt
    exit 0
  fi
  for i in $LIST; do
     if [ $file = $i ]; then
        less ./doc/$i
        exit 0
     fi
  done
  echo "wrong input, try again or type ^D to quit"
done

