#
# (C) Copyright 1992, ..., 2004 the "DOSEMU-Development-Team".
#
# for details see file COPYING in the DOSEMU distribution
#

top_builddir=../../../..
include $(top_builddir)/Makefile.conf

CFILES = dma.c
HFILES = 
DEPENDS= dma.d

ALL = $(CFILES) $(HFILES) README.dma

SUBDIR=dma

OBJS = dma.o


all: lib

install:

include $(REALTOPDIR)/src/Makefile.common
