#
# (C) Copyright 1992, ..., 2007 the "DOSEMU-Development-Team".
#
# for details see file COPYING.DOSEMU in the DOSEMU distribution
#

top_builddir=../../../..
include $(top_builddir)/Makefile.conf

CFILES = dma.c dmanew.c
HFILES = 
DEPENDS= dma.d dmanew.d

ALL = $(CFILES) $(HFILES) README.dma

OBJS = dma.o dmanew.o


all: lib

install:

include $(REALTOPDIR)/src/Makefile.common
