// Warning: autogenerated

asm(
	".data\n"
	".globl _binary_dpmisel_o_bin_start\n"
#if defined(__ELF__) || defined(__EMSCRIPTEN__)
	".size _binary_dpmisel_o_bin_start,0\n"
#endif
	"_binary_dpmisel_o_bin_start:\n"
	".incbin \"dpmisel.o.bin\"\n"
	".globl _binary_dpmisel_o_bin_end\n"
#if defined(__ELF__) || defined(__EMSCRIPTEN__)
	".size _binary_dpmisel_o_bin_end,0\n"
#endif
	"_binary_dpmisel_o_bin_end:\n"
#ifdef __ELF__
	".previous\n"
#endif
);
#include "/home/user/dosemu2/src/dosext/dpmi/dpmisel_offsets.h"
const unsigned DPMI_sel_code_start = 0x0000;
const unsigned DPMI_raw_mode_switch_pm = 0x0000;
const unsigned DPMI_save_restore_pm = 0x0001;
const unsigned DPMI_API_extension = 0x0003;
const unsigned DPMI_return_from_pm = 0x0005;
const unsigned DPMI_return_from_exception = 0x0006;
const unsigned DPMI_return_from_rm_callback = 0x0007;
const unsigned DPMI_exception = 0x0008;
const unsigned DPMI_interrupt = 0x0028;
const unsigned DPMI_return_from_RSPcall_exit = 0x0128;
const unsigned DPMI_return_from_ext_exception = 0x0129;
const unsigned DPMI_return_from_int_1c = 0x012a;
const unsigned DPMI_return_from_int_23 = 0x012b;
const unsigned DPMI_return_from_int_24 = 0x012c;
const unsigned DPMI_return_from_RSPcall = 0x012d;
const unsigned DPMI_return_from_rm_ext_exception = 0x012e;
const unsigned DPMI_return_from_rm_exception = 0x012f;
const unsigned DPMI_ext_exception = 0x0130;
const unsigned DPMI_rm_exception = 0x0150;
const unsigned DPMI_return_from_LDTExitCall = 0x0170;
const unsigned DPMI_reinit = 0x0171;
const unsigned DPMI_dj64 = 0x0172;
const unsigned DPMI_shlock = 0x0174;
const unsigned DPMI_return_from_LDTcall = 0x0183;
const unsigned DPMI_return_from_LDTcall16 = 0x018b;
const unsigned DPMI_sel_end = 0x0194;
const unsigned MSDOS_pmc_start = 0x0194;
const unsigned MSDOS_fault = 0x0194;
const unsigned MSDOS_pagefault = 0x0196;
const unsigned MSDOS_API_call = 0x0198;
const unsigned MSDOS_API_WINOS2_call = 0x019a;
const unsigned MSDOS_LDT_call16 = 0x019c;
const unsigned MSDOS_LDT_call32 = 0x019e;
const unsigned MSDOS_RSP_call16 = 0x01a0;
const unsigned MSDOS_RSP_call32 = 0x01a2;
const unsigned MSDOS_rmcb_call_start = 0x01a4;
const unsigned MSDOS_rmcb_call0 = 0x01a4;
const unsigned MSDOS_rmcb_ret0 = 0x01a5;
const unsigned MSDOS_rmcb_call1 = 0x01a7;
const unsigned MSDOS_rmcb_ret1 = 0x01a8;
const unsigned MSDOS_rmcb_call2 = 0x01aa;
const unsigned MSDOS_rmcb_ret2 = 0x01ab;
const unsigned MSDOS_rmcb_call_end = 0x01ad;
const unsigned MSDOS_hlt_start = 0x01ad;
const unsigned MSDOS_hlt_end = 0x01ed;
const unsigned MSDOS_pmc_end = 0x01ed;
const unsigned DPMI_VXD_start = 0x01ed;
const unsigned DPMI_VXD_VMM = 0x01ed;
const unsigned DPMI_VXD_PageFile = 0x01ef;
const unsigned DPMI_VXD_Reboot = 0x01f1;
const unsigned DPMI_VXD_VDD = 0x01f3;
const unsigned DPMI_VXD_VMD = 0x01f5;
const unsigned DPMI_VXD_VXDLDR = 0x01f7;
const unsigned DPMI_VXD_SHELL = 0x01f9;
const unsigned DPMI_VXD_VCD = 0x01fb;
const unsigned DPMI_VXD_VTD = 0x01fd;
const unsigned DPMI_VXD_CONFIGMG = 0x01ff;
const unsigned DPMI_VXD_ENABLE = 0x0201;
const unsigned DPMI_VXD_APM = 0x0203;
const unsigned DPMI_VXD_VTDAPI = 0x0205;
const unsigned DPMI_VXD_SOCK = 0x0207;
const unsigned DPMI_VXD_end = 0x0209;
const unsigned DPMI_call = 0x0209;
const unsigned DPMI_call_args = 0x020c;
const unsigned DPMI_call_args16 = 0x022c;
const unsigned DPMI_int2f = 0x024f;
const unsigned DPMI_msdos = 0x0252;
const unsigned DPMI_abort = 0x0255;
const unsigned DPMI_vtmr_irq = 0x025e;
const unsigned DPMI_vtmr_post_irq = 0x0265;
const unsigned DPMI_vrtc_irq = 0x0268;
const unsigned DPMI_vrtc_post_irq = 0x026f;
const unsigned DPMI_sel_code_end = 0x0272;
