// Warning: autogenerated

asm(
	".data\n"
	".globl _binary_bios_o_bin_start\n"
#if defined(__ELF__) || defined(__EMSCRIPTEN__)
	".size _binary_bios_o_bin_start,0\n"
#endif
	"_binary_bios_o_bin_start:\n"
	".incbin \"bios.o.bin\"\n"
	".globl _binary_bios_o_bin_end\n"
#if defined(__ELF__) || defined(__EMSCRIPTEN__)
	".size _binary_bios_o_bin_end,0\n"
#endif
	"_binary_bios_o_bin_end:\n"
#ifdef __ELF__
	".previous\n"
#endif
);
#include "/home/user/dosemu2/src/base/bios/x86/bios_offsets.h"
const unsigned bios_data_start = 0xe000;
const unsigned bios_f000_int10ptr = 0xed89;
const unsigned ROM_BIOS_EXIT = 0xe081;
const unsigned GET_RETCODE_HELPER = 0xe086;
const unsigned Mouse_ROUTINE_OFF = 0xe091;
const unsigned EOI2_OFF = 0xf6b5;
const unsigned IRET_OFF = 0xe0a2;
const unsigned FCB_HLP_OFF = 0xe0a3;
const unsigned INT10_WATCHER_OFF = 0xe0b0;
const unsigned bios_f000_int10_old = 0xe0b2;
const unsigned bios_in_int10_callback = 0xed8d;
const unsigned MOUSE_INT33_OFF = 0xe119;
const unsigned INT_RVC_33_OFF = 0xecc0;
const unsigned INT70_OFF = 0xe136;
const unsigned INT70_end = 0xe141;
const unsigned HD_parameter_table0 = 0xe401;
const unsigned HD_parameter_table1 = 0xe420;
const unsigned INT_RVC_21_OFF = 0xeab0;
const unsigned int_rvc_ip_21 = 0xeab2;
const unsigned int_rvc_cs_21 = 0xeab4;
const unsigned int_rvc_ret_ip_21 = 0xeabb;
const unsigned int_rvc_ret_cs_21 = 0xeabd;
const unsigned int_rvc_disp_ip_21 = 0xeabf;
const unsigned int_rvc_disp_cs_21 = 0xeac1;
const unsigned INT_RVC_28_OFF = 0xeb60;
const unsigned int_rvc_ip_28 = 0xeb62;
const unsigned int_rvc_cs_28 = 0xeb64;
const unsigned int_rvc_ret_ip_28 = 0xeb6b;
const unsigned int_rvc_ret_cs_28 = 0xeb6d;
const unsigned int_rvc_disp_ip_28 = 0xeb6f;
const unsigned int_rvc_disp_cs_28 = 0xeb71;
const unsigned INT_RVC_2f_OFF = 0xec10;
const unsigned int_rvc_ip_2f = 0xec12;
const unsigned int_rvc_cs_2f = 0xec14;
const unsigned int_rvc_ret_ip_2f = 0xec1b;
const unsigned int_rvc_ret_cs_2f = 0xec1d;
const unsigned int_rvc_disp_ip_2f = 0xec1f;
const unsigned int_rvc_disp_cs_2f = 0xec21;
const unsigned int_rvc_ip_33 = 0xecc2;
const unsigned int_rvc_cs_33 = 0xecc4;
const unsigned int_rvc_ret_ip_33 = 0xeccb;
const unsigned int_rvc_ret_cs_33 = 0xeccd;
const unsigned int_rvc_disp_ip_33 = 0xeccf;
const unsigned int_rvc_disp_cs_33 = 0xecd1;
const unsigned INT_RVC_e6_OFF = 0xed70;
const unsigned int_rvc_ip_e6 = 0xed72;
const unsigned int_rvc_cs_e6 = 0xed74;
const unsigned int_rvc_ret_ip_e6 = 0xed7b;
const unsigned int_rvc_ret_cs_e6 = 0xed7d;
const unsigned int_rvc_disp_ip_e6 = 0xed7f;
const unsigned int_rvc_disp_cs_e6 = 0xed81;
const unsigned DBGload_parblock = 0xed90;
const unsigned DBGload_CSIP = 0xeda2;
const unsigned PKTDRV_param = 0xeda6;
const unsigned PKTDRV_stats = 0xedb4;
const unsigned LFN_short_name = 0xedd0;
const unsigned bios_hlt_blk = 0xf100;
const unsigned DPMI_OFF = 0xf500;
const unsigned DPMI_dpmi_init = 0xf508;
const unsigned DPMI_return_from_dos = 0xf509;
const unsigned DPMI_return_from_rmint = 0xf50a;
const unsigned DPMI_return_from_realmode = 0xf52a;
const unsigned DPMI_return_from_dos_memory = 0xf54a;
const unsigned DPMI_int1c = 0xf54b;
const unsigned DPMI_int1c_end = 0xf5ab;
const unsigned DPMI_int23 = 0xf5ac;
const unsigned DPMI_int23_end = 0xf60c;
const unsigned DPMI_int23_1 = 0xf613;
const unsigned DPMI_int23_2 = 0xf616;
const unsigned DPMI_int24 = 0xf61b;
const unsigned DPMI_int24_end = 0xf67b;
const unsigned DPMI_raw_mode_switch_rm = 0xf67c;
const unsigned DPMI_save_restore_rm = 0xf67d;
const unsigned DPMI_exit = 0xf67f;
const unsigned DPMI_end = 0xf68f;
const unsigned DPMI_rmentry = 0xf68f;
const unsigned XMSControl_OFF = 0xf6a6;
const unsigned EOI_OFF = 0xf6ad;
const unsigned PKTDRV_OFF = 0xf6bf;
const unsigned PKTDRV_driver_name = 0xf6cb;
const unsigned PKTDRV_driver_entry_ip = 0xf6d8;
const unsigned PKTDRV_driver_entry_cs = 0xf6da;
const unsigned TCPDRV_OFF = 0xf6dc;
const unsigned TCPDRVR_OFF = 0xf6df;
const unsigned TCPDRV_driver_entry_ip = 0xf6f0;
const unsigned TCPDRV_driver_entry_cs = 0xf6f2;
const unsigned TCPDRV_driver_info = 0xf6f4;
const unsigned TCPDRV_session_info = 0xf814;
const unsigned TCPDRV_iface_name = 0xf824;
const unsigned FOSSIL_isr = 0xf834;
const unsigned FOSSIL_oldisr = 0xf836;
const unsigned FOSSIL_magic = 0xf83a;
const unsigned FOSSIL_maxfun = 0xf83c;
const unsigned FOSSIL_idstring = 0xf843;
const unsigned LFN_HELPER_OFF = 0xf85a;
const unsigned LFN_42_HELPER_OFF = 0xf871;
const unsigned LFN_A6_HELPER_OFF = 0xf876;
const unsigned DBGload_OFF = 0xf8a9;
const unsigned bios_text_font = 0xfa6e;
const unsigned INT75_OFF = 0xfea6;
const unsigned INT08_OFF = 0xfebd;
const unsigned INT71_OFF = 0xff36;
const unsigned bios_f000_end = 0x10000;
