#
# (C) Copyright 1992, ..., 2014 the "DOSEMU-Development-Team".
#
# for details see file COPYING in the DOSEMU distribution
#

top_builddir=../../..
include $(top_builddir)/Makefile.conf
ALL_CPPFLAGS += -I$(top_srcdir)/src/include/translate

CFILES = bg-mik.c cp1125.c cp1251.c cp737.c cp773.c cp775.c cp855.c cp857.c \
cp858.c cp860.c cp861.c cp862.c cp863.c cp864.c cp865.c cp866.c cp869.c \
cp874.c cp895.c iso8859-10.c iso8859-13.c iso8859-14.c iso8859-15.c koi8-r.c \
koi8-ru.c koi8-u.c mazovia.c

all: lib

include $(REALTOPDIR)/src/Makefile.common
