
top_builddir=../../../..
include $(top_builddir)/Makefile.conf


CFILES = pic.c
HFILES = 
DEPENDS= pic.d

ALL = $(CFILES) $(HFILES) README.pic

OBJS = pic.o


all: lib

install:

include $(REALTOPDIR)/src/Makefile.common
