#
# (C) Copyright 1992, ..., 2000 the "DOSEMU-Development-Team".
#
# for details see file COPYING in the DOSEMU distribution
#

CFILES = pic.c
HFILES = 
DEPENDS= pic.d

ALL = $(CFILES) $(HFILES) README.pic

SUBDIR=pic

OBJS = pic.o


all: lib

install:

include $(REALTOPDIR)/src/Makefile.common
