#
# (C) Copyright dosemu2 project.
#

top_builddir=../../../..
include $(top_builddir)/Makefile.conf

CFILES = vfs.c
SFILES =
ALL_CPPFLAGS += -I$(REALTOPDIR)/src/base/lib/fslib

include $(REALTOPDIR)/src/Makefile.common

all: lib
