#
# (C) Copyright 1992, ..., 2014 the "DOSEMU-Development-Team".
#
# for details see file COPYING.DOSEMU in the DOSEMU distribution
#

top_builddir=../../../..
include $(top_builddir)/Makefile.conf
ALL_CPPFLAGS += -I$(top_builddir)/src/arch/linux/mcontext

CFILES=pcl.c

include $(REALTOPDIR)/src/Makefile.common

all: lib
