// Warning: autogenerated

asm(
	".data\n"
	".globl _binary_vesabios_pm_o_bin_start\n"
#if defined(__ELF__) || defined(__EMSCRIPTEN__)
	".size _binary_vesabios_pm_o_bin_start,0\n"
#endif
	"_binary_vesabios_pm_o_bin_start:\n"
	".incbin \"vesabios_pm.o.bin\"\n"
	".globl _binary_vesabios_pm_o_bin_end\n"
#if defined(__ELF__) || defined(__EMSCRIPTEN__)
	".size _binary_vesabios_pm_o_bin_end,0\n"
#endif
	"_binary_vesabios_pm_o_bin_end:\n"
#ifdef __ELF__
	".previous\n"
#endif
);
#include "/home/user/dosemu2/src/base/dev/vga/vesabios_pm_offsets.h"
const unsigned vgaemu_bios_pm_interface = 0x0000;
const unsigned vgaemu_bios_pm_interface_end = 0x003e;
