
CFILES = sound.c
HFILES = sound.h $(REALTOPDIR)/include/sound.h 
DEPENDS= sound.d

ALL = $(CFILES) $(HFILES) README.sound TODO

SUBDIR=sound

OBJS = sound.o


all: lib

install:

include $(REALTOPDIR)/src/Makefile.common
