#!/bin/sh

#DEBHELPER#

case "$1" in
    configure)
#        chown dosemu2:dosemu2 /usr/libexec/dosemu2/dosemu2.bin
#        chmod ug+s /usr/libexec/dosemu2/dosemu2.bin
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
