#! /bin/bash
#
# (C) 2001 under GPL, Hans Lermen <lermen@fgan.de>
#
# Check for the right mtools version.
# Versions below 3.6 don't work with dosemu

set `mtools -V|awk '{print $3}'|tr '.,a-z' ' '`
MVER=$(( $1 * 10000 + $2 * 100))
if [ -n "$3" ]; then
  MVER=$(( $MVER + $3 ))
fi

if [ "$(( $MVER < 30600 ))"  = "1" ]; then
  echo "wrong mtools version installed, please upgrade to >= 3.6"
  exit 1
fi
exit 0

