// Warning: autogenerated

asm(
	".data\n"
	".globl _binary_kvmmon_o_bin_start\n"
#if defined(__ELF__) || defined(__EMSCRIPTEN__)
	".size _binary_kvmmon_o_bin_start,0\n"
#endif
	"_binary_kvmmon_o_bin_start:\n"
	".incbin \"kvmmon.o.bin\"\n"
	".globl _binary_kvmmon_o_bin_end\n"
#if defined(__ELF__) || defined(__EMSCRIPTEN__)
	".size _binary_kvmmon_o_bin_end,0\n"
#endif
	"_binary_kvmmon_o_bin_end:\n"
#ifdef __ELF__
	".previous\n"
#endif
);
#include "/home/user/dosemu2/src/base/emu-i386/kvmmon_offsets.h"
const unsigned kvm_mon_start = 0x0000;
const unsigned kvm_mon_hlt = 0x2013;
const unsigned kvm_mon_end = 0x202e;
