// Warning: autogenerated

asm(
	".data\n"
	".globl _binary_bootsect_o_bin_start\n"
#if defined(__ELF__) || defined(__EMSCRIPTEN__)
	".size _binary_bootsect_o_bin_start,0\n"
#endif
	"_binary_bootsect_o_bin_start:\n"
	".incbin \"bootsect.o.bin\"\n"
	".globl _binary_bootsect_o_bin_end\n"
#if defined(__ELF__) || defined(__EMSCRIPTEN__)
	".size _binary_bootsect_o_bin_end,0\n"
#endif
	"_binary_bootsect_o_bin_end:\n"
#ifdef __ELF__
	".previous\n"
#endif
);
#include "/home/user/dosemu2/src/plugin/periph/bootsect_offsets.h"
