#! /usr/bin/awk -f
#
# Parse the DOSEmu configuration file.
#

{
  var_end = index ($0, "=");
  var_type = substr ($0, 1, 1);
  var_name = substr ($0, 5, var_end -6);
  var_value = substr ($0, var_end+2, length($0) - var_end -1);

  if ( var_value ~ /^[\"\'\(][^\"\'\)]*[\"\'\)]$/ ) {
    if (substr (var_value, 2, 1) != "$") {
      var_value = substr (var_value, 2, length(var_value) - 2);
    }
  }
       
#  write_entry(var_name, var_type, escape_string(var_value) );
  write_entry(var_name, var_type, var_value );
}

