#
# (C) Copyright dosemu2 project.
#
# for details see file COPYING.DOSEMU in the DOSEMU distribution
#

top_builddir=../../../..
include $(top_builddir)/Makefile.conf

CFILES = fslib.c fslib_local.c

include $(REALTOPDIR)/src/Makefile.common

all: lib
