/* config.h, DOS emulator configuration file, Robert Sanders,
 * gt8134b@prism.gatech.edu, generated by dosconfig.c
 * 
 * DO NOT ALTER! "make config" will erase your changes!
 */

#ifndef CONFIG_H
#define CONFIG_H 1

#define    CONFIG_HOST     "pattern, NetBSD 1.1 NetBSD 1.1 (PATTERN) #0: Fri Nov 24 11:01:09 EST 1995     jtk@pattern:/u1/NetBSD-current/src/sys/arch/i386/compile/PATTERN"
#define    CONFIG_TIME     "Sun Nov 26 22:08:16 1995"
#define    CONFIG_FILE     "/etc/dosemu.conf"
#define    DOSEMU_USERS_FILE "/etc/dosemu.users"
#define    LIBSTART        0x20000000     
#define    VERSION         0              
#define    SUBLEVEL        63             
#define    PATCHLEVEL      0.1            
#define    VERSTR          "0.63.0.1"     

#endif /* config.h */

/* total defines:   9
 * end of configuration information
 */
