#
# (C) Copyright 1992, ..., 2000 the "DOSEMU-Development-Team".
#
# for details see file COPYING in the DOSEMU distribution
#

CFILES = sound.c
HFILES = 
DEPENDS= sound.d

ALL = $(CFILES) $(HFILES) README.sound TODO

SUBDIR=sound

OBJS = sound.o


all: lib

install:

include $(REALTOPDIR)/src/Makefile.common
