
top_builddir=../../..
include $(top_builddir)/Makefile.conf


CFILES = sound.c
HFILES = 
DEPENDS= sound.d

ALL = $(CFILES) $(HFILES) README.sound TODO

OBJS = sound.o


all: lib

install:

include $(REALTOPDIR)/src/Makefile.common
