name: Manual ASAN
on:
  workflow_dispatch:

jobs:
  manual_asan:
    name: Manual (ASAN)
    uses: ./.github/workflows/ci-build.yml
    with:
      bldtype: 'asan'
      runtype: 'simple'
      os: 'ubuntu-24.04'
