name: Manual FULL
on:
  workflow_dispatch:

jobs:
  manual_full:
    name: Manual (FULL)
    uses: ./.github/workflows/ci-build.yml
    with:
      bldtype: 'standard'
      runtype: 'full'
      os: 'ubuntu-24.04'
