name: Manual Normal
on:
  workflow_dispatch:

jobs:
  manual_normal:
    name: Manual (Normal)
    uses: ./.github/workflows/test-suite-worker.yml
    with:
      bldtype: 'standard'
      runtype: 'normal'
      os: 'ubuntu-24.04'
