name: Test Suite (Triggered)

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

on:
  push:

  pull_request:
    types:
      - opened
      - reopened
      - synchronize

# workflow_dispatch:

jobs:
  triggered:
    name: "Test Suite (standard-${{ (github.event_name == 'push' && github.repository_owner == 'dosemu' && github.ref_name == 'devel') && 'simple' || 'normal' }}-ubuntu-26.04)"
    uses: ./.github/workflows/test-suite-worker.yml
    with:
      bldtype: 'standard'
      runtype: ${{ (github.event_name == 'push' && github.repository_owner == 'dosemu' && github.ref_name == 'devel') && 'simple' || 'normal' }}
      os: 'ubuntu-26.04'
