name: Test Suite (Triggered)

on:
  push:

  pull_request:
    types:
      - opened
      - reopened
      - synchronize

# workflow_dispatch:

jobs:
  triggered:
    name: Test Suite (standard-normal-ubuntu-22.04)
    if: (github.event_name != 'push' || github.repository_owner != 'dosemu2')
    uses: ./.github/workflows/test-suite-worker.yml
    with:
      bldtype: 'standard'
      runtype: 'normal'
      os: 'ubuntu-22.04'
