name: Worker
on:
  workflow_call:
    inputs:
      bldtype:
        required: true
        type: string
      runtype:
        required: true
        type: string
      os:
        required: true
        type: string

jobs:
  worker:
    runs-on: ${{ inputs.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 50

    - name: Package install
      run: ./ci_prereq.sh

    - name: Build or install software under test
      env:
        BLDTYPE: ${{ inputs.bldtype }}
        RUNTYPE: ${{ inputs.runtype }}
        OS: ${{ inputs.os }}
      run: ./ci_build_or_install.sh

    - name: Cache binaries
      uses: actions/cache@v4
      env:
        cache-name: test-binaries
      with:
        path: ~/cache
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-

    - name: Add an ACL for ourselves
      run: |
          echo 'SUBSYSTEM=="misc", KERNEL=="kvm", RUN+="/usr/bin/setfacl -m u:'${USER}':rw- /dev/kvm"' | sudo tee /etc/udev/rules.d/99-kvm4dosemu2.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

    - name: Install test prerequisites
      id: test_prereq
      run: ./ci_test_prereq.sh

    - name: Open Watcom install
      uses: open-watcom/setup-watcom@v0
      with:
        version: 2.0-64

    - name: Test
      id: test
      env:
        BLDTYPE: ${{ inputs.bldtype }}
        RUNTYPE: ${{ inputs.runtype }}
        OS: ${{ inputs.os }}
        BASE_SHA: ${{ github.event.pull_request.base.sha }}
      run: ./ci_test.sh

    - name: Upload failure logs
      if: ${{ always() && (steps.test.outcome == 'failure') }}
      uses: actions/upload-artifact@v4
      with:
        name: failure-logs-${{ format('{0}-{1}-{2}', inputs.bldtype, inputs.runtype, inputs.os) }}
        path: test_*
