#!/usr/bin/python3

import argparse
import os
import subprocess
import sys
import zipfile
from pathlib import Path

SCRIPT_ROOT = os.path.dirname(os.path.abspath(__file__))

parser = argparse.ArgumentParser()
parser.add_argument("source", type=str, help="source directory containing DOS installation files")
parser.add_argument("destination", type=str, help="destination root directory")

args = parser.parse_args()

# system installation
cmddir = os.path.dirname(os.path.abspath(__file__)) + '/../share/dosemu/commands'
if not Path(cmddir + 'fdconfig.sys').is_file():
    # running from within source tree
    cmddir = os.path.dirname(os.path.abspath(__file__))

# Detect which DOS is provided and run the appropriate installation routine
for filename in Path(args.source).glob('*.zip'):
    for entry in zipfile.ZipFile(filename).namelist():
        if entry == 'BIN/': # found a freedos archive
            sys.exit(subprocess.run([SCRIPT_ROOT + '/dosemu-installfreedos', args.source, args.destination]).returncode)

if Path(args.source + '/msdos.sys').exists():
    sys.exit(subprocess.run([SCRIPT_ROOT + '/dosemu-installmsdos', args.source, args.destination]).returncode)

if list(Path(args.source).glob('opendos-hdimage*.rpm')):
    sys.exit(subprocess.run([SCRIPT_ROOT + '/dosemu-installopendos', args.source, args.destination]).returncode)

print('No DOS installation files were found.')
print('Run loaddosinstall as root to download a version of DOS.')
sys.exit(1)
