#!/usr/bin/python3

import os
import shutil
import subprocess
import sys

doschoices = []
completed_process = subprocess.run(['dosemu-downloaddos', '-l'], stdout=subprocess.PIPE)
if (completed_process.returncode != 0):
    sys.exit(completed_process.returncode)
print('DOSEMU2 DOS installer script\n\nPick the DOS to install:')
for dosline in completed_process.stdout.decode(sys.stdout.encoding).splitlines():
    dos = dosline.split(' ', 1)
    print(str(len(doschoices) + 1) + '. ' + dos[1])
    doschoices.append(dos[0])
print('0. Quit')

choice = ''
while not choice.isdigit() or int(choice) > len(doschoices):
    choice = input('[0-' + str(len(doschoices)) + '] ')

if int(choice) <= 0:
    print('Quitting... no DOS was installed.')
    sys.exit()

tmp_dir = '/tmp/' + os.path.basename(sys.argv[0]) + '-' + os.environ['USER'] + '-' + str(os.getpid())
if (subprocess.run(['dosemu-downloaddos', '-d', doschoices[int(choice) - 1], tmp_dir]).returncode == 0):
    subprocess.run(['dosemu-installdos', tmp_dir, os.environ['HOME'] + '/.dosemu/drive_c'])
    shutil.rmtree(tmp_dir)
