#!/bin/sh

FREEDOS_DEFAULT_MIRROR=https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files
TOSEC_IBM_PC_MIRROR=https://archive.org/download/IBM_PC_Compatibles_TOSEC_2012_04_23/IBM_PC_Compatibles_TOSEC_2012_04_23.zip

FREEDOS_BASE_URL=$FREEDOS_DEFAULT_MIRROR/distributions/1.1/repos/base
FREEDOS_ARCHIVES="kernel command assign attrib choice comp debug defrag deltree diskcomp diskcopy display \
edit edlin exe2bin fc find format help label mem mode more move nansi replace share shsucdx \
sort swsubst tree xcopy"

BWBASIC_URL=${FREEDOS_DEFAULT_MIRROR}/devel/basic/bwbasic/bwb220ax.zip
LIB_URL=${FREEDOS_DEFAULT_MIRROR}/devel/tools/lib-sk32.zip
TOUCH_URL=${FREEDOS_DEFAULT_MIRROR}/util/file/touch/1.44/touch144.zip
WCD_URL=${FREEDOS_DEFAULT_MIRROR}/util/user/wcd/wcd530b.zip

INSTALL_DIR=/var/lib/dosemu/install
DRIVE_ROOT="$1"
TMP_DIR=/tmp/"`basename $0`-$USER-$$"

download_file()
{
  SOURCE=$1
  DESTINATION=$2
  if [ -f "$DESTINATION" ]
  then
    echo "$DESTINATION" found, not redownloading
  else
    echo Downloading "$SOURCE"...
    wget --quiet "$SOURCE" -O "$DESTINATION"
  fi
}

download_FREEDOS_ARCHIVES()
{
  DEST=$1
  echo Downloading FreeDOS...
  mkdir -p "${DEST}"
  for filename in ${FREEDOS_ARCHIVES}
  do
    download_file "${FREEDOS_BASE_URL}"/"$filename".zip "${DEST}"/"$filename".zip
  done

  download_file "${BWBASIC_URL}" "${DEST}"/bwbasic.zip
  download_file "${LIB_URL}" "${DEST}"/lib.zip
  download_file "${TOUCH_URL}" "${DEST}"/touch.zip
  download_file "${WCD_URL}" "${DEST}"/wcd.zip

  echo Downloading done
}

extract_7z()
{
  ARCHIVE="$1"
  FILENAME="$2"
  DESTINATION=$3
  echo Extracting $FILENAME
  7z e "$ARCHIVE" $FILENAME -o"$DESTINATION" -y -ssc- >/dev/null
}

download_and_extract()
{
  IMGURL=$1
  IMGCNT=$2
  DEST=$3

  mkdir -p "$TMP_DIR" "$DEST"
  for i in $(seq 1 "$IMGCNT")
  do
    download_file "`printf "$IMGURL" "$i"`" $TMP_DIR/disk$i.zip
    mkdir $TMP_DIR/ex$i
    extract_7z $TMP_DIR/disk$i.zip "" $TMP_DIR/ex$i
    IMAGE="${TMP_DIR}/ex$i/`ls \"${TMP_DIR}\"/ex$i/`"
    MTOOLS_LOWER_CASE=1 mcopy -sn -i "$IMAGE" ::* $DEST
  done
  rm -r "$TMP_DIR"
}

verify_root()
{
  if [ "$(id -u)" -ne "0" ] ; then
    echo "Please run $0 as root"
    exit 1;
  fi
}

verify_tool()
{
  EXECUTABLE=$1
  PACKAGE=$2
  if [ ! `which "$EXECUTABLE"` ] ; then
    echo Please install "$PACKAGE" and make sure that "$EXECUTABLE" is on your PATH.
    exit 1
  fi
}

verify_system()
{
  verify_tool wget wget
  verify_tool 7z 7zip
  verify_tool mcopy mtools
}

verify_noexistinginstall()
{
  DEST=$1
  if [ -n "$(ls -A $DEST)" ] ; then
    echo "There is a already an existing set of DOS installation files in $DEST."
    exit 1
  fi
}

download_dos()
{
  DOS_FLAVOUR=$1
  DESTINATION=$2
  case $DOS_FLAVOUR in
    "freedos11")
      download_FREEDOS_ARCHIVES $DESTINATION
      ;;
    "msdos622")
      verify_tool msexpand libmspack
      download_and_extract $TOSEC_IBM_PC_MIRROR/IBM%%20PC%%20Compatibles%%20%%5BTOSEC%%5D%%2FIBM%%20PC%%20Compatibles%%20-%%20Operating%%20Systems%%20-%%20%%5BIMA%%5D%%20%%28TOSEC-v2011-01-06_CM%%29%%2FMicrosoft%%20MS-DOS%%20v6.22%%20%%281994%%29%%28Microsoft%%29%%28Disk%%20%d%%20of%%203%%29.zip 3 $DESTINATION
      ;;
  esac
}

verify_system

while getopts ld: OPT; do
    case "$OPT" in
        l) # print list
            echo freedos11 FreeDOS 1.1 \(2011\)
            echo msdos622 Microsoft MS-DOS v6.22 \(1994\)
            exit 0
            ;;
        d) # download the specified DOS
            download_dos $OPTARG $3
            exit 0
            ;;
    esac
done
