#!/bin/sh

FREEDOS_DEFAULT_MIRROR=https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files
TOSEC_IBM_PC_MIRROR=https://archive.org/download/IBM_PC_Compatibles_TOSEC_2012_04_23/IBM_PC_Compatibles_TOSEC_2012_04_23.zip
OPENLINUX_MIRROR=ftp://ftp.nvg.org/pub/mirrors/metalab.unc.edu/distributions/caldera

FREEDOS_BASE_URL=$FREEDOS_DEFAULT_MIRROR/distributions
FREEDOS11_URL=$FREEDOS_BASE_URL/1.1
FREEDOS12_URL=$FREEDOS_BASE_URL/1.2
FREEDOS_ARCHIVES="kernel command assign attrib choice comp debug defrag deltree diskcomp diskcopy display \
edit edlin exe2bin fc find format help label mem mode more move nansi replace share shsucdx \
sort swsubst tree xcopy"

BWBASIC_URL=${FREEDOS_DEFAULT_MIRROR}/devel/basic/bwbasic/bwb220ax.zip
LIB_URL=${FREEDOS_DEFAULT_MIRROR}/devel/tools/lib-sk32.zip
TOUCH_URL=${FREEDOS_DEFAULT_MIRROR}/util/file/touch/1.44/touch144.zip
WCD_URL=${FREEDOS_DEFAULT_MIRROR}/util/user/wcd/wcd530b.zip

INSTALL_DIR=/var/lib/dosemu/install
DRIVE_ROOT="$1"
TMP_DIR=/tmp/"`basename $0`-$USER-$$"

download_file()
{
  SOURCE=$1
  DESTINATION_FILE=$2
  if [ -f "$DESTINATION_FILE" ]
  then
    echo "$DESTINATION_FILE" found, not redownloading
  else
    echo Downloading "$SOURCE"...
    wget --quiet "$SOURCE" -O "$DESTINATION_FILE"
  fi
}

download_FREEDOS_ARCHIVES()
{
  FREEDOS_URL=$1
  echo Downloading FreeDOS...
  for filename in ${FREEDOS_ARCHIVES}
  do
    download_file "${FREEDOS_URL}"/repos/base/"$filename".zip "${DESTINATION}"/"$filename".zip
  done

  download_file "${BWBASIC_URL}" "${DESTINATION}"/bwbasic.zip
  download_file "${LIB_URL}" "${DESTINATION}"/lib.zip
  download_file "${TOUCH_URL}" "${DESTINATION}"/touch.zip
  download_file "${WCD_URL}" "${DESTINATION}"/wcd.zip

  echo Downloading done
}

extract_7z()
{
  ARCHIVE="$1"
  FILENAME="$2"
  DESTINATION_DIR=$3
  echo Extracting $FILENAME
  7z e "$ARCHIVE" $FILENAME -o"$DESTINATION_DIR" -y -ssc- >/dev/null
}

download_and_extract()
{
  IMGURL=$1
  IMGCNT=$2

  mkdir -p "$TMP_DIR"
  for i in $(seq 1 "$IMGCNT")
  do
    download_file "`printf "$IMGURL" "$i"`" $TMP_DIR/disk$i.zip
    mkdir $TMP_DIR/ex$i
    extract_7z $TMP_DIR/disk$i.zip "" $TMP_DIR/ex$i
    IMAGE="${TMP_DIR}/ex$i/`ls \"${TMP_DIR}\"/ex$i/`"
    MTOOLS_LOWER_CASE=1 mcopy -sn -i "$IMAGE" ::* $DESTINATION
  done
  rm -r "$TMP_DIR"
}

verify_root()
{
  if [ "$(id -u)" -ne "0" ] ; then
    echo "Please run $0 as root"
    exit 1;
  fi
}

verify_tool()
{
  EXECUTABLE=$1
  PACKAGE=$2
  if [ ! `which "$EXECUTABLE"` ] ; then
    echo Please install "$PACKAGE" and make sure that "$EXECUTABLE" is on your PATH.
    exit 1
  fi
}

verify_system()
{
  verify_tool wget wget
  verify_tool 7z 7zip
  verify_tool mcopy mtools
}

verify_noexistinginstall()
{
  if [ -n "$(ls -A $DESTINATION)" ] ; then
    echo "There is a already an existing set of DOS installation files in $DESTINATION."
    exit 1
  fi
}

download_dos()
{
  DOS_FLAVOUR=$1
  
  mkdir -p "${DESTINATION}"
  
  case $DOS_FLAVOUR in
    "freedos12")
      download_FREEDOS_ARCHIVES ${FREEDOS12_URL}
      ;;
    "freedos11")
      download_FREEDOS_ARCHIVES ${FREEDOS11_URL}
      ;;
    "msdos622")
      download_and_extract $TOSEC_IBM_PC_MIRROR/IBM%%20PC%%20Compatibles%%20%%5BTOSEC%%5D%%2FIBM%%20PC%%20Compatibles%%20-%%20Operating%%20Systems%%20-%%20%%5BIMA%%5D%%20%%28TOSEC-v2011-01-06_CM%%29%%2FMicrosoft%%20MS-DOS%%20v6.22%%20%%281994%%29%%28Microsoft%%29%%28Disk%%20%d%%20of%%203%%29.zip 3 $DESTINATION
      ;;
    "opendos702")
      download_file $OPENLINUX_MIRROR/updates/OpenLinux/1.3/current/SRPMS/opendos-hdimage-7.02-4.src.rpm $DESTINATION/opendos-hdimage-7.02-4.src.rpm
      if [ "$(sha512sum < $DESTINATION/opendos-hdimage-7.02-4.src.rpm)" = "174f7c12e07c301189a59a53ba99912a8c3f2579319984cc2a26d25a4e9b27a6227e8b18516c88525794cd260112528f7e6957c5438be6e9a345c9dcbb01ef27  -" ]
      then
        echo Verified non-secure download $DESTINATION/opendos-hdimage-7.02-4.src.rpm
      else
        echo There was a problem downloading OpenDOS. The downloaded archive could not be verified.
        exit 1
      fi
      ;;

  esac
}

verify_system

while getopts ld: OPT; do
    case "$OPT" in
        l) # print list
            echo freedos12 FreeDOS 1.2 \(2016\)
            echo freedos11 FreeDOS 1.1 \(2011\)
            echo msdos622 Microsoft MS-DOS v6.22 \(1994\)
            echo opendos702 Caldera OpenDOS 7.02 \(1997\)
            exit 0
            ;;
        d) # download the specified DOS
            DESTINATION=$3
            download_dos $OPTARG
            exit 0
            ;;
    esac
done
